### ISSUE TITLE
While signing up, the "Register - Step : 2" screen - Improper UI

### ISSUE THREAD

**Issue by mturakhia** [divyang7777/gnan-g#9]
- The title of the page should be: "REGISTER - STEP : 2" instead of "REGISTER - STEP: 2"

- Under profile data, The email id is not completely visible:
![screenshot_2019-02-28-22-52-50-528_com mba sheelquotient](https://user-images.githubusercontent.com/48099253/53585571-3ae4d600-3bac-11e9-95e0-ab6a032bd8b5.png)

- The last field label and it's helptext should be Confirm Password instead of Verify Password.

- In Password, enter 1st digit --> It displays message "Password must contain at least six..." 
  Expected: The full message should be displayed.  ("...." should not be displayed)

- If entered Password is Abcdef--> Displays incorrect messsage: "Passwords must contain Uppercase,.."
  Expected: Displayed message should be "Password must contain atleast 1 letter" and all validations 
  should be fully visible. ("...." should not be displayed)

- If Password and confirm Password do not match the message should be: "Password and Confirm Password must be same" instead of "Password and verifypassword must be same."

**- Observation : Enter incorrect password combinations 6 times and submit and then enter the password in correct format and then submit --> Displays Red Screen and app crashed**

**Comment by milanvadher** [comment]
Fixed ...
